//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int prdt_id { get; set; }
        public string prdt_name { get; set; }
        public decimal prdt_price { get; set; }
        public int prdt_qty { get; set; }
        public string prdt_img { get; set; }
    }
}
